apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: saas-web-app-hpa
  namespace: saas-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: saas-web-app
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
        - type: Percent
          value: 100
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 1
          periodSeconds: 120
